/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BasesSpotlightPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  propertyHeights: {},
  propertyOrder: []
};
var SpotlightView = class extends import_obsidian.BasesView {
  constructor(controller, containerEl, plugin) {
    super(controller);
    this.type = "bases-spotlight-view";
    this.currentIndex = 0;
    this.sidebarVisible = true;
    this.sidebarWidth = 300;
    this.isResizing = false;
    this.activePdfBlobUrls = [];
    this.doResize = (e) => {
      if (!this.isResizing) return;
      const containerRect = this.containerEl.getBoundingClientRect();
      const newWidth = containerRect.right - e.clientX;
      if (newWidth > 100 && newWidth < containerRect.width - 100) {
        this.sidebarWidth = newWidth;
        this.sidebarEl.setCssStyles({ width: `${this.sidebarWidth}px` });
      }
    };
    this.stopResize = () => {
      this.isResizing = false;
      activeDocument.removeEventListener("mousemove", this.doResize);
      activeDocument.removeEventListener("mouseup", this.stopResize);
    };
    this.plugin = plugin;
    this.containerEl = containerEl;
    this.containerEl.tabIndex = 0;
    this.wrapperEl = this.containerEl.createDiv("spotlight-bases-wrapper");
    this.centerEl = this.wrapperEl.createDiv("spotlight-center");
    const resizerEl = this.wrapperEl.createDiv("spotlight-resizer");
    resizerEl.addEventListener("mousedown", (e) => this.initResize(e));
    this.sidebarEl = this.wrapperEl.createDiv("spotlight-sidebar");
    this.containerEl.addEventListener("keydown", (e) => this.handleKeyDown(e));
    const toggleBtn = this.containerEl.createEl("button", {
      text: "Toggle Sidebar",
      cls: "spotlight-sidebar-toggle"
    });
    toggleBtn.addEventListener("click", () => this.toggleSidebar());
    const fullscreenBtn = this.containerEl.createEl("button", {
      text: "Full Screen",
      cls: "spotlight-fullscreen-toggle"
    });
    fullscreenBtn.addEventListener("click", () => {
      if (!activeDocument.fullscreenElement) {
        this.containerEl.requestFullscreen().catch((_err) => {
          console.error(`Error attempting to enable fullscreen: ${err.message}`);
        });
      } else {
        activeDocument.exitFullscreen().catch(console.error);
      }
    });
    activeDocument.addEventListener("fullscreenchange", () => {
      if (activeDocument.fullscreenElement === this.containerEl) {
        fullscreenBtn.setText("Exit Full Screen");
        this.containerEl.addClass("spotlight-is-fullscreen");
      } else {
        fullscreenBtn.setText("Full Screen");
        this.containerEl.removeClass("spotlight-is-fullscreen");
      }
    });
  }
  onDataUpdated() {
    this.render();
  }
  get filteredEntries() {
    if (!this.data || !this.data.data) return [];
    return this.data.data.filter((entry) => {
      const file = entry.file;
      if (file instanceof import_obsidian.TFile && file.extension !== "md") {
        const sidecarPath = file.path + ".md";
        if (this.app.vault.getAbstractFileByPath(sidecarPath)) {
          return false;
        }
      }
      return true;
    });
  }
  toggleSidebar() {
    this.sidebarVisible = !this.sidebarVisible;
    if (this.sidebarVisible) {
      this.sidebarEl.setCssStyles({ display: "flex" });
    } else {
      this.sidebarEl.setCssStyles({ display: "none" });
    }
  }
  initResize(e) {
    this.isResizing = true;
    activeDocument.addEventListener("mousemove", this.doResize);
    activeDocument.addEventListener("mouseup", this.stopResize);
  }
  handleKeyDown(e) {
    const entries = this.filteredEntries;
    if (!entries.length) return;
    if (e.key === "ArrowRight" || e.key === "ArrowDown") {
      this.currentIndex = Math.min(this.currentIndex + 1, entries.length - 1);
      this.render();
      e.preventDefault();
    } else if (e.key === "ArrowLeft" || e.key === "ArrowUp") {
      this.currentIndex = Math.max(this.currentIndex - 1, 0);
      this.render();
      e.preventDefault();
    }
  }
  render() {
    this.centerEl.empty();
    this.sidebarEl.empty();
    const entries = this.filteredEntries;
    if (!entries.length) {
      this.centerEl.createEl("div", { text: "No entries found.", cls: "spotlight-empty" });
      return;
    }
    if (this.currentIndex >= entries.length) {
      this.currentIndex = entries.length - 1;
    }
    if (this.currentIndex < 0) {
      this.currentIndex = 0;
    }
    const entry = entries[this.currentIndex];
    let shouldRenderProperty = false;
    let valueStr = "";
    const spotlightProperty = this.config.get("spotlight_property");
    const centerContentEl = this.centerEl.createDiv("spotlight-center-content");
    if (spotlightProperty && spotlightProperty !== "") {
      const propValue = entry.getValue(spotlightProperty);
      valueStr = this.formatValue(propValue);
      if (valueStr !== "") {
        shouldRenderProperty = true;
      }
    }
    if (shouldRenderProperty) {
      const linkMatch = valueStr.match(/\[\[(.*?)\]\]/);
      if (linkMatch) {
        const linkText = linkMatch[1];
        const linkPath = linkText.split("|")[0];
        const destFile = this.app.metadataCache.getFirstLinkpathDest(linkPath, entry.file instanceof import_obsidian.TFile ? entry.file.path : "");
        if (destFile instanceof import_obsidian.TFile) {
          this.renderFileContent(destFile, centerContentEl, this.currentIndex);
        } else {
          this.centerEl.removeClass("spotlight-center-no-padding");
          centerContentEl.empty();
          centerContentEl.addClass("spotlight-error-container");
          centerContentEl.createEl("div", { text: "\u2753", cls: "spotlight-error-icon" });
          centerContentEl.createEl("div", { text: `File not found: ${linkPath}`, cls: "spotlight-error-message" });
        }
      } else {
        this.centerEl.removeClass("spotlight-center-no-padding");
        centerContentEl.empty();
        centerContentEl.addClass("spotlight-error-container");
        centerContentEl.createEl("div", { text: "\u2753", cls: "spotlight-error-icon" });
        centerContentEl.createEl("div", { text: `File not found: ${valueStr}`, cls: "spotlight-error-message" });
      }
    } else {
      let file = entry.file;
      if (file instanceof import_obsidian.TFile) {
        this.renderFileContent(file, centerContentEl, this.currentIndex);
      } else {
        this.centerEl.removeClass("spotlight-center-no-padding");
        centerContentEl.createEl("div", { text: "Cannot read file content." });
      }
    }
    this.sidebarEl.setCssStyles({ width: `${this.sidebarWidth}px` });
    const sidebarTitle = this.sidebarEl.createEl("h3", { text: "Attributes" });
    sidebarTitle.addClass("spotlight-sidebar-title");
    let properties = [...this.data.properties || []];
    const orderMap = /* @__PURE__ */ new Map();
    this.plugin.settings.propertyOrder.forEach((p, i) => orderMap.set(p, i));
    properties.sort((a, b) => {
      const indexA = orderMap.has(a) ? orderMap.get(a) : Infinity;
      const indexB = orderMap.has(b) ? orderMap.get(b) : Infinity;
      return indexA - indexB;
    });
    let targetFile = entry.file;
    if (!(targetFile instanceof import_obsidian.TFile)) return;
    if (!targetFile) return;
    let isBinary = targetFile.extension !== "md";
    let sidecarFile = null;
    if (isBinary) {
      const sidecarPath = targetFile.path + ".md";
      const sc = this.app.vault.getAbstractFileByPath(sidecarPath);
      if (sc instanceof import_obsidian.TFile) sidecarFile = sc;
    }
    for (const prop of properties) {
      let val = entry.getValue(prop);
      if (!val && sidecarFile && prop.startsWith("note.")) {
        const propName = prop.substring(5);
        const cache = this.app.metadataCache.getFileCache(sidecarFile);
        if ((cache == null ? void 0 : cache.frontmatter) && cache.frontmatter[propName] !== void 0) {
          val = cache.frontmatter[propName];
        }
      }
      const propEl = this.sidebarEl.createDiv("spotlight-property");
      propEl.dataset.prop = prop;
      const propNameEl = propEl.createDiv({ text: this.getPropName(prop), cls: "spotlight-property-name" });
      propNameEl.draggable = true;
      propNameEl.setCssStyles({ cursor: "grab" });
      propNameEl.addEventListener("dragstart", (e) => {
        var _a;
        (_a = e.dataTransfer) == null ? void 0 : _a.setData("text/plain", prop);
        propEl.classList.add("spotlight-property-dragging");
      });
      propNameEl.addEventListener("dragend", () => {
        propEl.classList.remove("spotlight-property-dragging");
        this.sidebarEl.querySelectorAll(".spotlight-property-drag-over").forEach((el) => el.classList.remove("spotlight-property-drag-over"));
        this.sidebarEl.querySelectorAll(".spotlight-property-drag-below").forEach((el) => el.classList.remove("spotlight-property-drag-below"));
      });
      propEl.addEventListener("dragover", (e) => {
        e.preventDefault();
        const rect = propEl.getBoundingClientRect();
        const midY = rect.top + rect.height / 2;
        if (e.clientY < midY) {
          propEl.classList.add("spotlight-property-drag-over");
          propEl.classList.remove("spotlight-property-drag-below");
        } else {
          propEl.classList.add("spotlight-property-drag-below");
          propEl.classList.remove("spotlight-property-drag-over");
        }
      });
      propEl.addEventListener("dragleave", () => {
        propEl.classList.remove("spotlight-property-drag-over");
        propEl.classList.remove("spotlight-property-drag-below");
      });
      propEl.addEventListener("drop", (e) => {
        const doDrop = async () => {
          var _a;
          e.preventDefault();
          propEl.classList.remove("spotlight-property-drag-over");
          propEl.classList.remove("spotlight-property-drag-below");
          const draggedProp = (_a = e.dataTransfer) == null ? void 0 : _a.getData("text/plain");
          if (!draggedProp || draggedProp === prop) return;
          const rect = propEl.getBoundingClientRect();
          const midY = rect.top + rect.height / 2;
          const insertAfter = e.clientY >= midY;
          const currentOrder = [...properties];
          const fromIndex = currentOrder.indexOf(draggedProp);
          if (fromIndex > -1) currentOrder.splice(fromIndex, 1);
          let toIndex = currentOrder.indexOf(prop);
          if (insertAfter) toIndex++;
          currentOrder.splice(toIndex, 0, draggedProp);
          this.plugin.settings.propertyOrder = currentOrder;
          await this.plugin.saves();
          this.render();
        };
        doDrop().catch(console.error);
      });
      const valContainerEl = propEl.createDiv({ cls: "spotlight-property-value-container" });
      if (this.plugin.settings.propertyHeights[prop]) {
        valContainerEl.setCssStyles({ height: `${this.plugin.settings.propertyHeights[prop]}px`, maxHeight: "none" });
      }
      const valEl = valContainerEl.createDiv({ cls: "spotlight-property-value spotlight-scrollable-text" });
      const resizerEl = propEl.createDiv("spotlight-property-resizer");
      resizerEl.draggable = false;
      let startY = 0;
      let startHeight = 0;
      const onMouseMove = (e) => {
        const newHeight = Math.max(20, startHeight + (e.clientY - startY));
        valContainerEl.setCssStyles({ height: `${newHeight}px`, maxHeight: "none" });
      };
      const onMouseUp = () => {
        const doMouseUp = async () => {
          activeDocument.removeEventListener("mousemove", onMouseMove);
          activeDocument.removeEventListener("mouseup", onMouseUp);
          window.setTimeout(() => {
            this.isResizing = false;
          }, 50);
          const currentHeight = valContainerEl.getBoundingClientRect().height;
          this.plugin.settings.propertyHeights[prop] = currentHeight;
          await this.plugin.saves();
        };
        doMouseUp().catch(console.error);
      };
      resizerEl.addEventListener("mousedown", (e) => {
        e.preventDefault();
        e.stopPropagation();
        this.isResizing = true;
        startY = e.clientY;
        startHeight = valContainerEl.getBoundingClientRect().height;
        activeDocument.addEventListener("mousemove", onMouseMove);
        activeDocument.addEventListener("mouseup", onMouseUp);
      });
      resizerEl.addEventListener("click", (e) => {
        e.preventDefault();
        e.stopPropagation();
      });
      let isEmpty = false;
      if (val && typeof val.renderTo === "function") {
        val.renderTo(valEl, this.app.renderContext);
        if (valEl.innerHTML === "") isEmpty = true;
      } else {
        const formatted = this.formatValue(val);
        if (formatted === "") isEmpty = true;
        else valEl.setText(formatted);
      }
      if (isEmpty) {
        valEl.setText("\u2014");
        valEl.setCssStyles({ color: "var(--text-faint)" });
      }
      const hyperlinkProperty = this.config.get("hyperlink_property");
      if (hyperlinkProperty && prop === hyperlinkProperty) {
        propEl.title = "Click to open file (Ctrl/Cmd+Click for new pane)";
        valEl.addClass("spotlight-hyperlink-value");
        propEl.addEventListener("click", (e) => {
          if (this.isResizing || e.target.closest(".spotlight-property-resizer")) return;
          if (entry.file instanceof import_obsidian.TFile) {
            const newLeaf = e.ctrlKey || e.metaKey || e.button === 1;
            this.app.workspace.getLeaf(newLeaf).openFile(entry.file);
          }
        });
      } else if (prop.startsWith("note.") && entry.file instanceof import_obsidian.TFile) {
        propEl.title = "Click to edit";
        propEl.setCssStyles({ cursor: "pointer" });
        propEl.addEventListener("click", (e) => {
          const doClick = async () => {
            var _a, _b, _c;
            if (this.isResizing || e.target.closest(".spotlight-property-resizer")) return;
            if (valContainerEl.querySelector(".spotlight-property-edit-input")) return;
            const propName = prop.substring(5);
            let originalFile = entry.file;
            if (!(originalFile instanceof import_obsidian.TFile)) return;
            let targetIsBinary = originalFile.extension !== "md";
            let sidecarPath = targetIsBinary ? originalFile.path + ".md" : null;
            let sidecar = sidecarPath ? this.app.vault.getAbstractFileByPath(sidecarPath) instanceof import_obsidian.TFile ? this.app.vault.getAbstractFileByPath(sidecarPath) : null : null;
            let fileToRead = targetIsBinary ? sidecar : originalFile;
            let rawValue = void 0;
            if (fileToRead instanceof import_obsidian.TFile) {
              const cache = this.app.metadataCache.getFileCache(fileToRead);
              rawValue = (_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a[propName];
            }
            const typeManager = this.app.metadataTypeManager;
            const propType = (_c = (_b = typeManager == null ? void 0 : typeManager.getPropertyInfo) == null ? void 0 : _b.call(typeManager, propName)) == null ? void 0 : _c.type;
            const isCheckbox = propType === "checkbox" || typeof rawValue === "boolean";
            if (isCheckbox) {
              let fileToEdit = fileToRead;
              if (!fileToEdit && sidecarPath) {
                const newFile = await this.app.vault.create(sidecarPath, "");
                fileToEdit = newFile instanceof import_obsidian.TFile ? newFile : null;
              }
              if (fileToEdit instanceof import_obsidian.TFile) {
                this.app.fileManager.processFrontMatter(fileToEdit, (fm) => {
                  fm[propName] = !rawValue;
                });
              }
              return;
            }
            const editValue = rawValue !== void 0 ? typeof rawValue === "object" ? JSON.stringify(rawValue) : String(rawValue) : "";
            valContainerEl.empty();
            const inputEl = valContainerEl.createEl("textarea", { cls: "spotlight-property-edit-input" });
            inputEl.value = editValue;
            inputEl.focus();
            const save = async () => {
              const newValStr = inputEl.value;
              let parsedVal = newValStr;
              try {
                if (newValStr.startsWith("[") || newValStr.startsWith("{")) {
                  parsedVal = JSON.parse(newValStr);
                } else if (newValStr === "true") parsedVal = true;
                else if (newValStr === "false") parsedVal = false;
                else if (!isNaN(Number(newValStr)) && newValStr !== "") parsedVal = Number(newValStr);
              } catch (_err) {
              }
              let fileToEdit = fileToRead;
              if (!fileToEdit && sidecarPath) {
                if (newValStr === "") {
                  this.render();
                  return;
                }
                const newFile = await this.app.vault.create(sidecarPath, "");
                fileToEdit = newFile instanceof import_obsidian.TFile ? newFile : null;
              }
              if (fileToEdit instanceof import_obsidian.TFile) {
                await this.app.fileManager.processFrontMatter(fileToEdit, (fm) => {
                  if (newValStr === "") {
                    delete fm[propName];
                  } else {
                    fm[propName] = parsedVal;
                  }
                });
              }
              if (fileToEdit !== originalFile) {
                window.setTimeout(() => this.render(), 100);
              }
            };
            inputEl.addEventListener("blur", save);
            inputEl.addEventListener("keydown", (e2) => {
              if (e2.key === "Enter" && !e2.shiftKey) {
                e2.preventDefault();
                inputEl.blur();
              } else if (e2.key === "Escape") {
                e2.preventDefault();
                this.render();
              }
            });
          };
          doClick().catch(console.error);
        });
      }
    }
    const navContainerEl = this.sidebarEl.createDiv("spotlight-nav-container");
    const prevBtn = navContainerEl.createEl("button", { text: "Previous", cls: "spotlight-nav-btn" });
    prevBtn.disabled = this.currentIndex === 0;
    prevBtn.addEventListener("click", () => {
      this.currentIndex = Math.max(this.currentIndex - 1, 0);
      this.render();
    });
    const countEl = navContainerEl.createDiv("spotlight-count");
    countEl.setText(`Entry ${this.currentIndex + 1} of ${entries.length}`);
    const nextBtn = navContainerEl.createEl("button", { text: "Next", cls: "spotlight-nav-btn" });
    nextBtn.disabled = this.currentIndex === entries.length - 1;
    nextBtn.addEventListener("click", () => {
      this.currentIndex = Math.min(this.currentIndex + 1, entries.length - 1);
      this.render();
    });
  }
  formatValue(val) {
    if (val === null || val === void 0) return "";
    if (typeof val === "object") {
      if (Array.isArray(val)) return val.map((v) => this.formatValue(v)).join(", ");
      if (val.value !== void 0) return this.formatValue(val.value);
      try {
        return JSON.stringify(val);
      } catch (e) {
        return String(val);
      }
    }
    return String(val);
  }
  getPropName(propId) {
    const parts = propId.split(".");
    return parts.length > 1 ? parts.slice(1).join(".") : propId;
  }
  renderFileContent(file, containerEl, renderIndex) {
    this.activePdfBlobUrls.forEach((url) => URL.revokeObjectURL(url));
    this.activePdfBlobUrls = [];
    const sidecarMatch = file.name.match(/^(.*\.(png|jpg|jpeg|gif|bmp|svg|webp|pdf))\.md$/i);
    if (sidecarMatch) {
      const originalPath = file.path.slice(0, -3);
      const originalFile = this.app.vault.getAbstractFileByPath(originalPath);
      if (originalFile instanceof import_obsidian.TFile) {
        file = originalFile;
      }
    }
    const ext = file.extension.toLowerCase();
    const imageExtensions = ["png", "jpg", "jpeg", "gif", "bmp", "svg", "webp"];
    if (imageExtensions.includes(ext) || ext === "pdf") {
      this.centerEl.addClass("spotlight-center-no-padding");
    } else {
      this.centerEl.removeClass("spotlight-center-no-padding");
    }
    if (imageExtensions.includes(ext)) {
      containerEl.empty();
      containerEl.addClass("spotlight-center-media-container");
      const resourcePath = this.app.vault.getResourcePath(file);
      containerEl.createEl("img", { attr: { src: resourcePath }, cls: "spotlight-media" });
    } else if (ext === "pdf") {
      containerEl.empty();
      containerEl.addClass("spotlight-center-pdf-container");
      this.app.vault.readBinary(file).then((buffer) => {
        if (this.currentIndex !== renderIndex) return;
        const blob = new Blob([buffer], { type: "application/pdf" });
        const url = URL.createObjectURL(blob);
        this.activePdfBlobUrls.push(url);
        containerEl.createEl("iframe", {
          cls: "spotlight-pdf-iframe",
          attr: {
            src: url,
            type: "application/pdf"
          }
        });
      }).catch((_err) => {
        if (this.currentIndex !== renderIndex) return;
        containerEl.empty();
        containerEl.createEl("div", { text: `Could not load PDF content for ${file.name}.` });
      });
    } else {
      this.app.vault.cachedRead(file).then((content) => {
        if (this.currentIndex !== renderIndex) return;
        const codeBlocks = [];
        let modifiedContent = content.replace(/(```[\s\S]*?```|`[^`]*`)/g, (match) => {
          codeBlocks.push(match);
          return `__SPOTLIGHT_CODE_BLOCK_${codeBlocks.length - 1}__`;
        });
        modifiedContent = modifiedContent.replace(/!\[\[(.*?)\]\]/g, (match, p1) => {
          const cleanSrc = p1.split("|")[0].split("#")[0];
          if (cleanSrc.toLowerCase().endsWith(".pdf")) {
            const heightMatch = p1.match(/height=(\d+)/);
            const height = heightMatch ? heightMatch[1] : "800";
            return `<div class="spotlight-pdf-placeholder" data-src="${p1}" style="height: ${height}px; width: 100%;"></div>`;
          }
          return match;
        });
        modifiedContent = modifiedContent.replace(/!\[(.*?)\]\((.*?)\)/g, (match, p1, p2) => {
          const cleanSrc = p2.split("|")[0].split("#")[0];
          if (cleanSrc.toLowerCase().endsWith(".pdf")) {
            const heightMatch = p2.match(/height=(\d+)/);
            const height = heightMatch ? heightMatch[1] : "800";
            return `<div class="spotlight-pdf-placeholder" data-src="${p2}" style="height: ${height}px; width: 100%;"></div>`;
          }
          return match;
        });
        modifiedContent = modifiedContent.replace(/__SPOTLIGHT_CODE_BLOCK_(\d+)__/g, (match, p1) => {
          return codeBlocks[parseInt(p1, 10)];
        });
        containerEl.empty();
        containerEl.addClass("markdown-rendered", "markdown-preview-view");
        import_obsidian.MarkdownRenderer.render(this.app, modifiedContent, containerEl, file.path, this).then(() => {
          if (this.currentIndex !== renderIndex) return;
          const placeholders = containerEl.querySelectorAll(".spotlight-pdf-placeholder");
          placeholders.forEach((placeholder) => {
            const src = placeholder.getAttribute("data-src");
            if (!src) return;
            const cleanSrc = src.split("|")[0].split("#")[0];
            const destFile = this.app.metadataCache.getFirstLinkpathDest(cleanSrc, file.path);
            if (destFile instanceof import_obsidian.TFile && destFile.extension.toLowerCase() === "pdf") {
              this.app.vault.readBinary(destFile).then((buffer) => {
                if (this.currentIndex !== renderIndex) return;
                const blob = new Blob([buffer], { type: "application/pdf" });
                const url = URL.createObjectURL(blob);
                this.activePdfBlobUrls.push(url);
                placeholder.empty();
                placeholder.createEl("iframe", {
                  cls: "spotlight-pdf-iframe",
                  attr: {
                    src: url,
                    type: "application/pdf"
                  }
                });
              });
            }
          });
        });
      }).catch((_err) => {
        if (this.currentIndex !== renderIndex) return;
        containerEl.empty();
        containerEl.createEl("div", { text: `Could not load content for ${file.name}.` });
      });
    }
  }
};
var BasesSpotlightPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loads();
    this.registerBasesView("bases-spotlight-view", {
      name: "Spotlight View",
      icon: "presentation",
      factory: (controller, containerEl) => {
        const view = new SpotlightView(controller, containerEl, this);
        return view;
      },
      options: (config) => [
        {
          type: "property",
          key: "spotlight_property",
          displayName: "Spotlight Content Property",
          // @ts-ignore
          description: "Select an attribute to display in the center instead of the page content"
        },
        {
          type: "property",
          key: "hyperlink_property",
          displayName: "Hyperlink Property",
          // @ts-ignore
          description: "Select an attribute to display as a clickable link that opens the file"
        }
      ]
    });
  }
  onunload() {
  }
  async loads() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saves() {
    await this.saveData(this.settings);
  }
};

/* nosourcemap */